import { TRegistrationForm } from "@/types";

export const API_BASE_URL =
  "https://snc-services.sncformer.com/dev/iCRS/api/public/index.php/api";

// export const API_BASE_URL =
//   "http://10.1.8.94:8081/dev/iCRS-ACC-All/CRS_Acc/public/index.php/api";

export const queryKey = {
  //! for register new customer
  GET_USER: "GET_USER",
  GET_BUSINESS_TYPE_LIST: "GET_BUSINESS_TYPE_LIST",
  GET_DOCUMENT_KEY_LIST: "GET_DOCUMENT_KEY_LIST",
  GET_CERTIFICATED_LIST: "GET_CERTIFICATED_LIST",
  GET_BENEFITS_LIST: "GET_BENEFITS_LIST",
  GET_DELIVERY_TERMS_LIST: "GET_DELIVERY_TERMS_LIST",
  GET_COMPANY_POLICY_LIST: "GET_COMPANY_POLICY_LIST",
  GET_COMPANY_LIST: "GET_COMPANY_LIST",
  CREATE_REGISTER_ID: "CREATE_REGISTER_ID",
  GET_COUNTRY_CODE_LIST: "GET_COUNTRY_CODE_LIST",
  CREATE_NEW_CUSTOMER: "CREATE_NEW_CUSTOMER",
  GET_DOC_BY_REGIS_ID: "GET_DOC_BY_REGIS_ID",
  UPLOAD_FILE: "UPLOAD_FILE",
  GET_REGIS_LIST: "GET_REGIS_LIST",
  GET_REGIS_BY_ID: "GET_REGIS_BY_ID",
  DELETE_DOC_BY_ID: "DELETE_DOC_BY_ID",
  UPDATE_REGIS_BY_ID: "UPDATE_REGIS_BY_ID",
  GET_REGIS_BY_ACCOUNT_ID: "GET_REGIS_BY_ACCOUNT_ID",

  //! for general assessment
  GET_APPROVALS_BY_ID: "GET_APPROVALS_BY_ID",
  GET_TEMPLATE_GENERAL_ASSESSMENT_BY_ID:
    "GET_TEMPLATE_GENERAL_ASSESSMENT_BY_ID",
  CREATE_GENERAL_ASSESSMENT: "CREATE_GENERAL_ASSESSMENT",
  UPDATE_GENERAL_ASSESSMENT: "UPDATE_GENERAL_ASSESSMENT",

  //! Utils
  GET_COMMENT_BY_REGIS_ID: "GET_COMMENT_BY_REGIS_ID",
  GET_COMMENT_BY_REGIS_ID_R3: "GET_COMMENT_BY_REGIS_ID_R3",
  CREATE_COMMENT: "CREATE_COMMENT",

  //! DBD
  GET_SYNC_DBD: "GET_SYNC_DBD",
  CONFIRM_DBD_INFO: "CONFIRM_DBD_INFO",
  GET_DBD_INFO: "GET_DBD_INFO",

  //! R3
  GET_FINANCIAL_RATIO: "GET_FINANCIAL_RATIO",

  //! Approvals & Action
  SENT_TO_EDIT: "SENT_TO_EDIT",
  SENT_TO_SUSPEND: "SENT_TO_SUSPEND",
  ENTER_CUSTOMER_CODE: "ENTER_CUSTOMER_CODE",
  SENT_TO_APPROVE: "SENT_TO_APPROVE",
  SENT_TO_REJECT: "SENT_TO_REJECT",

  //! Summary
  GET_SUMMARY_BY_REGIS_ID_PART_1: "GET_SUMMARY_BY_REGIS_ID_PART_1",
  GET_SUMMARY_BY_REGIS_ID_PART_2: "GET_SUMMARY_BY_REGIS_ID_PART_2",
  GET_COMPANY_PROFILE: "GET_COMPANY_PROFILE",

  //! Overview
  GET_ASSESSMENT_RESULT_REGIS_COUN: "GET_ASSESSMENT_RESULT_REGIS_COUN",
  GET_MAIN_CUSTOMER_RATIO: "GET_MAIN_CUSTOMER_RATIO",
  GET_SHARE_HOLDER_RATIO: "GET_SHARE_HOLDER_RATIO",
  GET_OBJECTIVE_PURCHASING_RATIO: "GET_OBJECTIVE_PURCHASING_RATIO",
  GET_REGIS_STAT: "GET_REGIS_STAT",

  //! Import excel
  POST_IMPORT_EXCEL_FINANCIAL_POSITION: "POST_IMPORT_EXCEL_FINANCIAL_POSITION",
  POST_IMPORT_EXCEL_ICOME_STATEMENT: "POST_IMPORT_EXCEL_ICOME_STATEMENT",
  POST_IMPORT_EXCEL_FINANCIAL_RATIOS: "POST_IMPORT_EXCEL_FINANCIAL_RATIOS",

  //! Import excel
  GET_REGIS_BY_ID_EXTERNAL: "GET_REGIS_BY_ID_EXTERNAL",
  SENT_INVITE_TO_EXTERNAL: "SENT_INVITE_TO_EXTERNAL",
};

export const LatitudesLongitudes = {
  RAYONG: {
    latitude: 12.884494672509366,
    longitude: 101.0954191548317,
  },
  SAMUTPRAKARN: {
    latitude: 13.54395677386411,
    longitude: 100.78228050617567,
  },
};

export const KEY_LOCAL_STORAGE = {
  ICRS_ADMIN_LOCAL_STORAGE: "ICRS_ADMIN_LOCAL_STORAGE",
};

export const PRIMARY_COLOR = "#2563EB";

export const MODE_CODE = {
  CREATE: "CREATE",
  EDIT: "EDIT",
  VIEW: "VIEW",
};

export const CheckCustomerForeigner = (
  customerInfo: TRegistrationForm,
): boolean => {
  const {
    company_information: {
      company_registration: { is_thai },
    },
  } = customerInfo;
  return is_thai ? false : true;
};

export const RAYONG_PLANT = [""];
