export const API_BASE_URL =
  "http://10.1.8.94:8081/dev/iCRS-ACC-All/CRS_Acc/public/index.php/api";

export const queryKey = {
  GET_USER: "GET_USER",
  GET_BUSINESS_TYPE_LIST: "GET_BUSINESS_TYPE_LIST",
  GET_DOCUMENT_KEY_LIST: "GET_DOCUMENT_KEY_LIST",
  GET_CERTIFICATED_LIST: "GET_CERTIFICATED_LIST",
  GET_BENEFITS_LIST: "GET_BENEFITS_LIST",
  GET_DELIVERY_TERMS_LIST: "GET_DELIVERY_TERMS_LIST",
  GET_COMPANY_POLICY_LIST: "GET_COMPANY_POLICY_LIST",
  GET_COMPANY_LIST: "GET_COMPANY_LIST",
};

export const LatitudesLongitudes = {
  RAYONG: {
    latitude: 12.884494672509366,
    longitude: 101.0954191548317,
  },
  SAMUTPRAKARN: {
    latitude: 13.54395677386411,
    longitude: 100.78228050617567,
  },
};

export const KEY_LOCAL_STORAGE = {
  ICRS_ADMIN_LOCAL_STORAGE: "ICRS_ADMIN_LOCAL_STORAGE",
};

export const PRIMARY_COLOR = "#1E88E5";
